version: "3"

services:
  frontend:
    image: calculatorfrontend:latest
    # build: .
    volumes:
      - type: bind
        source: ./
        target: /usr/local/tomcat/webapps/calc
    ports:
      - 9999:8080
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - 9200:9200
  #   #   - 9300:9300
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.13.0
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  #   ports:
  #     - '5601:5601'
networks:
  default:
    name: cnd-calculator